#!/usr/bin/env node

const parse = require('./src/parse-all')

let line = ''

process.stdin.setEncoding('utf8');

process.stdin.on('readable', () => {
  let chunk;
  // Use a loop to make sure we read all available data.
  while ((chunk = process.stdin.read()) !== null) {
    line += chunk
  }
});

process.stdin.on('end', () => {
  process.stdout.write(JSON.stringify(parse(line)))
});

